
## variable groups -----
var_groups <- list(
  "Ctotal_gCm2" = "Carbon Stocks",
  "som_gCm2" = "Soil",
  "dom_gCm2" = "DOM",
  "foliage_gCm2" = "Foliage",
  "labile_gCm2" = "Labile",
  "wood_gCm2" = "Wood",
  "litter_gCm2" = "Litter",
  "biomass_gCm2" = "Biomass",
  "alloc_foliage_gCm2day" = "Foliage",
  "alloc_labile_gCm2day" = "Labile",
  "alloc_roots_gCm2day" = "Roots",
  "alloc_wood_gCm2day" = "Wood",
  "dCbiomass_gCm2" = "Biomass",
  "dCdom_gCm2" = "DOM",
  "dCfoliage_gCm2" = "Foliage",
  "dClabile_gCm2" = "Labile",
  "dClitter_gCm2" = "Litter",
  "dCroots_gCm2" = "Roots",
  "dCsom_gCm2" = "Soil",
  "dCwood_gCm2" = "Wood",
  "nbe_gCm2day" = "Carbon Exchange",
  "nbp_gCm2day" = "Primary Production",
  "nee_gCm2day" = "Carbon Exchange",
  "npp_gCm2day" = "Primary Production",
  "gpp_gCm2day" = "Primary Production",
  "rauto_gCm2day" = "Respiration",
  "reco_gCm2day" = "Respiration",
  "rhet_gCm2day" = "Respiration",
  "fire_gCm2day" = "Fire",
  "FIREemiss_biomass_gCm2day" = "Fire",
  "FIREemiss_dom_gCm2day" = "Fire",
  "FIREemiss_foliage_gCm2day" = "Fire",
  "FIREemiss_labile_gCm2day" = "Fire",
  "FIREemiss_litter_gCm2day" = "Fire",
  "FIREemiss_roots_gCm2day" = "Fire",
  "FIREemiss_som_gCm2day" = "Fire",
  "FIREemiss_wood_gCm2day" = "Fire",
  "dSurfWater_kgH2Om2" = "Water",
  "dwSWP_MPa" = "Water",
  "ET_kgH2Om2day" = "Water",
  "Esoil_kgH2Om2day" = "Water",
  "Etrans_kgH2Om2day" = "Water",
  "Ewetcanopy_kgH2Om2day" = "Water",
  "runoff_kgH2Om2day" = "Water",
  "snow_kgH2Om2" = "Snow",
  "total_drainage_kgH2Om2day" = "Water",
  "wue_eco_gCkgH2O" = "Water",
  "wue_plant_gCkgH2O" = "Water",
  "CiCa" = "Gas Exchange",
  "gs_mmolH2Om2s" = "Gas Exchange",
  "gb_mmolH2Om2s" = "Gas Exchange",
  "gs_demand_supply_ratio" = "Gas Exchange",
  "foliage_to_litter_gCm2day" = "Turnover",
  "litter_to_som_gCm2day" = "Turnover",
  "labile_to_foliage_gCm2day" = "Turnover",
  "biomass_to_litter_gCm2day" = "Turnover",
  "wood_to_litter_gCm2day" = "Turnover",
  "roots_to_litter_gCm2day" = "Turnover",
  "harvest_gCm2day" = "Harvest",
  "HARVESTextracted_biomass_gCm2day" = "Harvest",
  "HARVESTextracted_wood_gCm2day" = "Harvest",
  "HARVESTextracted_foliage_gCm2day" = "Harvest",
  "HARVESTextracted_roots_gCm2day" = "Harvest",
  "HARVESTextracted_litter_gCm2day" = "Harvest",
  "HARVESTextracted_labile_gCm2day" = "Harvest",
  "HARVESTextracted_som_gCm2day" = "Harvest",
  "lai_m2m2" = "Canopy",
  "dRootDepth_m" = "Structure"
)

# Palette assignment by group
group_palettes <- list(
  "Carbon Stocks" = "viridis",
  "Carbon Exchange" = "turbo",
  "Soil" = "lipari",
  "DOM" = "cividis",
  "Foliage" = "bamako", # need to figure out how to reverse this one
  "Labile" = "acton",
  "Litter" = "cividis",
  "Roots" = "devon",
  "Biomass" = "imola",
  "Wood" = "bamako",
  "Primary Production" = "navia",
  "Respiration" = "rocket",
  "Fire" = "inferno",
  "Water" = "mako",
  "Snow" = "oslo",
  "Gas Exchange" = "magma",
  "Turnover" = "bilbao",
  "Harvest" = "batlow",
  "Canopy" = "tokyo",
  "Structure" = "turku"
)






# old version: 
# 
# 
# ## Variable groups ----
# var_groups <- list(
#   "Ctotal_gCm2" = "Carbon Stocks",
#   "som_gCm2" = "Carbon Stocks",
#   "dom_gCm2" = "Carbon Stocks",
#   "foliage_gCm2" = "Carbon Stocks",
#   "labile_gCm2" = "Carbon Stocks",
#   "wood_gCm2" = "Carbon Stocks",
#   "litter_gCm2" = "Carbon Stocks",
#   "biomass_gCm2" = "Carbon Stocks",
#   "alloc_foliage_gCm2day" = "Carbon Stocks",
#   "alloc_labile_gCm2day" = "Carbon Stocks",
#   "alloc_roots_gCm2day" = "Carbon Stocks",
#   "alloc_wood_gCm2day" = "Carbon Stocks",
#   
#   "dCbiomass_gCm2" = "Carbon Fluxes",
#   "dCdom_gCm2" = "Carbon Fluxes",
#   "dCfoliage_gCm2" = "Carbon Fluxes",
#   "dClabile_gCm2" = "Carbon Fluxes",
#   "dClitter_gCm2" = "Carbon Fluxes",
#   "dCroots_gCm2" = "Carbon Fluxes",
#   "dCsom_gCm2" = "Carbon Fluxes",
#   "dCwood_gCm2" = "Carbon Fluxes",
#   "nbe_gCm2day" = "Carbon Fluxes",
#   "nbp_gCm2day" = "Carbon Fluxes",
#   "nee_gCm2day" = "Carbon Fluxes",
#   "npp_gCm2day" = "Carbon Fluxes",
#   
#   "fire_gCm2day" = "Fire",
#   "FIREemiss_biomass_gCm2day" = "Fire",
#   "FIREemiss_dom_gCm2day" = "Fire",
#   "FIREemiss_foliage_gCm2day" = "Fire",
#   "FIREemiss_labile_gCm2day" = "Fire",
#   "FIREemiss_litter_gCm2day" = "Fire",
#   "FIREemiss_roots_gCm2day" = "Fire",
#   "FIREemiss_som_gCm2day" = "Fire",
#   "FIREemiss_wood_gCm2day" = "Fire",
#   
#   "dSurfWater_kgH2Om2" = "Water & Soil",
#   "dwSWP_MPa" = "Water & Soil",
#   "ET_kgH2Om2day" = "Water & Soil",
#   "Esoil_kgH2Om2day" = "Water & Soil",
#   "Etrans_kgH2Om2day" = "Water & Soil",
#   "Ewetcanopy_kgH2Om2day" = "Water & Soil",
#   "runoff_kgH2Om2day" = "Water & Soil",
#   "snow_kgH2Om2" = "Water & Soil",
#   "total_drainage_kgH2Om2day" = "Water & Soil",
#   "wue_eco_gCkgH2O" = "Water & Soil",
#   "wue_plant_gCkgH2O" = "Water & Soil",
#   
#   "CiCa" = "Gas Exchange",
#   "gpp_gCm2day" = "Gas Exchange",
#   "gs_mmolH2Om2s" = "Gas Exchange",
#   "gb_mmolH2Om2s" = "Gas Exchange",
#   "gs_demand_supply_ratio" = "Gas Exchange",
#   "rauto_gCm2day" = "Gas Exchange",
#   "reco_gCm2day" = "Gas Exchange",
#   "rhet_gCm2day" = "Gas Exchange",
#   
#   "foliage_to_litter_gCm2day" = "Turnover",
#   "litter_to_som_gCm2day" = "Turnover",
#   "labile_to_foliage_gCm2day" = "Turnover",
#   "biomass_to_litter_gCm2day" = "Turnover",
#   "wood_to_litter_gCm2day" = "Turnover",
#   "roots_to_litter_gCm2day" = "Turnover",
#   
#   "harvest_gCm2day" = "Harvest",
#   "HARVESTextracted_biomass_gCm2day" = "Harvest",
#   "HARVESTextracted_wood_gCm2day" = "Harvest",
#   "HARVESTextracted_foliage_gCm2day" = "Harvest",
#   "HARVESTextracted_roots_gCm2day" = "Harvest",
#   "HARVESTextracted_litter_gCm2day" = "Harvest",
#   "HARVESTextracted_labile_gCm2day" = "Harvest",
#   "HARVESTextracted_som_gCm2day" = "Harvest",
#   
#   "lai_m2m2" = "Canopy",
#   "dRootDepth_m" = "Structure"
# )
# 
# ## Group palettes ----
# group_palettes <- list(
#   "Carbon Stocks" = "viridis",
#   "Carbon Fluxes" = "plasma",
#   "Fire" = "inferno",
#   "Water & Soil" = "cividis",
#   "Gas Exchange" = "magma",
#   "Turnover" = "YlGnBu",
#   "Harvest" = "YlOrBr",
#   "Canopy" = "BrBG",
#   "Structure" = "PiYG"
# )